## International Debt Data
<p> The below lines of code connects us to the <code>debtDB</code> database where the table <code>international_debt</code> is residing.

In [2]:
import sqlalchemy as sq
sq.create_engine('sqlite:///debtDB.db')
%load_ext sql
%sql sqlite:///debtDB.db

## Q1. Print first 10 rows of data.

In [3]:
%%sql
SELECT *
FROM international_debt
LIMIT 10

 * sqlite:///debtDB.db
Done.

[('Afghanistan', 'AFG', 'Disbursements on external debt, long-term (DIS, current US$)', 'DT.DIS.DLXF.CD', 72894453.7),
 ('Afghanistan', 'AFG', 'Interest payments on external debt, long-term (INT, current US$)', 'DT.INT.DLXF.CD', 53239440.1),
 ('Afghanistan', 'AFG', 'PPG, bilateral (AMT, current US$)', 'DT.AMT.BLAT.CD', 61739336.9),
 ('Afghanistan', 'AFG', 'PPG, bilateral (DIS, current US$)', 'DT.DIS.BLAT.CD', 49114729.4),
 ('Afghanistan', 'AFG', 'PPG, bilateral (INT, current US$)', 'DT.INT.BLAT.CD', 39903620.1),
 ('Afghanistan', 'AFG', 'PPG, multilateral (AMT, current US$)', 'DT.AMT.MLAT.CD', 39107845),
 ('Afghanistan', 'AFG', 'PPG, multilateral (DIS, current US$)', 'DT.DIS.MLAT.CD', 23779724.3),
 ('Afghanistan', 'AFG', 'PPG, multilateral (INT, current US$)', 'DT.INT.MLAT.CD', 13335820),
 ('Afghanistan', 'AFG', 'PPG, official creditors (AMT, current US$)', 'DT.AMT.OFFT.CD', 100847181.9),
 ('Afghanistan', 'AFG', 'PPG, official creditors (DIS, current US$)', 'DT.DIS.OFFT.CD', 72894453.7)]

## Q2. Find the number of distinct countries.

In [9]:
%%sql
SELECT COUNT(DISTINCT country_name) AS total_distinct_countries
FROM international_debt

 * sqlite:///debtDB.db
Done.

[(124,)]

## Q3. Find out the distinct debt indicators.

In [10]:
%%sql 
SELECT DISTINCT indicator_code AS distinct_debt_indicators
FROM international_debt
ORDER BY distinct_debt_indicators

 * sqlite:///debtDB.db
Done.

[('DT.AMT.BLAT.CD',),
 ('DT.AMT.DLXF.CD',),
 ('DT.AMT.DPNG.CD',),
 ('DT.AMT.MLAT.CD',),
 ('DT.AMT.OFFT.CD',),
 ('DT.AMT.PBND.CD',),
 ('DT.AMT.PCBK.CD',),
 ('DT.AMT.PROP.CD',),
 ('DT.AMT.PRVT.CD',),
 ('DT.DIS.BLAT.CD',),
 ('DT.DIS.DLXF.CD',),
 ('DT.DIS.MLAT.CD',),
 ('DT.DIS.OFFT.CD',),
 ('DT.DIS.PCBK.CD',),
 ('DT.DIS.PROP.CD',),
 ('DT.DIS.PRVT.CD',),
 ('DT.INT.BLAT.CD',),
 ('DT.INT.DLXF.CD',),
 ('DT.INT.DPNG.CD',),
 ('DT.INT.MLAT.CD',),
 ('DT.INT.OFFT.CD',),
 ('DT.INT.PBND.CD',),
 ('DT.INT.PCBK.CD',),
 ('DT.INT.PROP.CD',),
 ('DT.INT.PRVT.CD',)]

## Q4. Find out the cumulative debt owed by all the countries.

In [11]:
%%sql
SELECT 
    ROUND(SUM (debt) / 1000000, 2) AS total_debt
FROM international_debt

 * sqlite:///debtDB.db
Done.

[(3079734.49,)]

## Q5. Find the country with highest debt.

In [12]:
%%sql
SELECT 
    country_name, 
    SUM(debt) AS total_debt
FROM international_debt
GROUP BY country_name
ORDER BY total_debt DESC
LIMIT 1

 * sqlite:///debtDB.db
Done.

[('China', 285793494734.2)]

## Q6. Find the average amount of debt across indicators.

In [13]:
%%sql
SELECT 
    indicator_code AS debt_indicator,
    indicator_name,
    AVG(debt) AS average_debt
FROM international_debt
GROUP BY debt_indicator, indicator_name
ORDER BY average_debt DESC

 * sqlite:///debtDB.db
Done.

[('DT.AMT.DLXF.CD', 'Principal repayments on external debt, long-term (AMT, current US$)', 5904868401.499195),
 ('DT.AMT.DPNG.CD', 'Principal repayments on external debt, private nonguaranteed (PNG) (AMT, current US$)', 5161194333.812659),
 ('DT.DIS.DLXF.CD', 'Disbursements on external debt, long-term (DIS, current US$)', 2152041216.8902435),
 ('DT.DIS.OFFT.CD', 'PPG, official creditors (DIS, current US$)', 1958983452.8598356),
 ('DT.AMT.PRVT.CD', 'PPG, private creditors (AMT, current US$)', 1803694101.963265),
 ('DT.INT.DLXF.CD', 'Interest payments on external debt, long-term (INT, current US$)', 1644024067.6508067),
 ('DT.DIS.BLAT.CD', 'PPG, bilateral (DIS, current US$)', 1223139290.39823),
 ('DT.INT.DPNG.CD', 'Interest payments on external debt, private nonguaranteed (PNG) (INT, current US$)', 1220410844.4215188),
 ('DT.AMT.OFFT.CD', 'PPG, official creditors (AMT, current US$)', 1191187963.083064),
 ('DT.AMT.PBND.CD', 'PPG, bonds (AMT, current US$)', 1082623947.6536236),
 ('DT.DIS.MLAT.CD', 'PPG, multilateral (DIS, current US$)', 839843678.6158334),
 ('DT.INT.PBND.CD', 'PPG, bonds (INT, current US$)', 804733376.5985507),
 ('DT.AMT.PROP.CD', 'PPG, other private creditors (AMT, current US$)', 746888800.477778),
 ('DT.AMT.PCBK.CD', 'PPG, commercial banks (AMT, current US$)', 734868742.6011907),
 ('DT.INT.PRVT.CD', 'PPG, private creditors (INT, current US$)', 719740180.0887755),
 ('DT.AMT.BLAT.CD', 'PPG, bilateral (AMT, current US$)', 712619634.6598358),
 ('DT.AMT.MLAT.CD', 'PPG, multilateral (AMT, current US$)', 490062193.49838716),
 ('DT.DIS.PRVT.CD', 'PPG, private creditors (DIS, current US$)', 311323264.69056594),
 ('DT.INT.OFFT.CD', 'PPG, official creditors (INT, current US$)', 297677338.95725805),
 ('DT.DIS.PCBK.CD', 'PPG, commercial banks (DIS, current US$)', 293305195.5941176),
 ('DT.INT.BLAT.CD', 'PPG, bilateral (INT, current US$)', 164093285.6090164),
 ('DT.INT.PCBK.CD', 'PPG, commercial banks (INT, current US$)', 156647613.0559524),
 ('DT.INT.MLAT.CD', 'PPG, multilateral (INT, current US$)', 136230719.2451613),
 ('DT.DIS.PROP.CD', 'PPG, other private creditors (DIS, current US$)', 81135160.7),
 ('DT.INT.PROP.CD', 'PPG, other private creditors (INT, current US$)', 34250651.23518519)]

## Q7. Which country has highest amount of principal repayment.

In [14]:
%%sql
SELECT 
    country_name, 
    indicator_name
FROM international_debt
WHERE debt = (SELECT 
                 MAX(debt)
             FROM international_debt
             WHERE indicator_code = 'DT.AMT.DLXF.CD')

 * sqlite:///debtDB.db
Done.

[('China', 'Principal repayments on external debt, long-term (AMT, current US$)')]

## Q8. Find out the frequency of debt indicators.

In [15]:
%%sql
SELECT indicator_code, COUNT(indicator_code) AS indicator_count
FROM international_debt
GROUP BY indicator_code
ORDER BY indicator_count DESC, indicator_code DESC

 * sqlite:///debtDB.db
Done.

[('DT.INT.OFFT.CD', 124),
 ('DT.INT.MLAT.CD', 124),
 ('DT.INT.DLXF.CD', 124),
 ('DT.AMT.OFFT.CD', 124),
 ('DT.AMT.MLAT.CD', 124),
 ('DT.AMT.DLXF.CD', 124),
 ('DT.DIS.DLXF.CD', 123),
 ('DT.INT.BLAT.CD', 122),
 ('DT.DIS.OFFT.CD', 122),
 ('DT.AMT.BLAT.CD', 122),
 ('DT.DIS.MLAT.CD', 120),
 ('DT.DIS.BLAT.CD', 113),
 ('DT.INT.PRVT.CD', 98),
 ('DT.AMT.PRVT.CD', 98),
 ('DT.INT.PCBK.CD', 84),
 ('DT.AMT.PCBK.CD', 84),
 ('DT.INT.DPNG.CD', 79),
 ('DT.AMT.DPNG.CD', 79),
 ('DT.INT.PBND.CD', 69),
 ('DT.AMT.PBND.CD', 69),
 ('DT.INT.PROP.CD', 54),
 ('DT.AMT.PROP.CD', 54),
 ('DT.DIS.PRVT.CD', 53),
 ('DT.DIS.PCBK.CD', 51),
 ('DT.DIS.PROP.CD', 19)]

## Q9. Find out the maximum debt owed by each country.

In [16]:
%%sql
SELECT country_name,
MAX(debt) AS maximum_debt
FROM international_debt
GROUP BY country_name
ORDER BY maximum_debt DESC

 * sqlite:///debtDB.db
Done.

[('China', 96218620835.7),
 ('Brazil', 90041840304.1),
 ('Russian Federation', 66589761833.5),
 ('Turkey', 51555031005.80001),
 ('South Asia', 48756295898.19999),
 ('Least developed countries: UN classification', 40160766261.6),
 ('IDA only', 34531188113.2),
 ('India', 31923507000.8),
 ('Indonesia', 30916112653.8),
 ('Kazakhstan', 27482093686.4),
 ('Mexico', 25218503927),
 ('Cameroon', 18186662060.4),
 ('Romania', 14013783350.4),
 ('Colombia', 11985674438.7),
 ('Angola', 11067045628.1),
 ('Venezuela, RB', 9878659207.2),
 ('Egypt, Arab Rep.', 9692114176.9),
 ('Lebanon', 9506919669.6),
 ('South Africa', 9474257551.9),
 ('Bangladesh', 9050557611.9),
 ('Vietnam', 8873505909.2),
 ('Pakistan', 8336013891.3),
 ('Ukraine', 8148995625.6),
 ('Philippines', 6479170917.7),
 ('Thailand', 5914706998.3),
 ('Peru', 5881259974.7),
 ('Sri Lanka', 5761489255.9),
 ('Morocco', 5153430846.8),
 ('Belarus', 4640037884.2),
 ('Kenya', 4266494939.7),
 ('Ecuador', 3623731570.2),
 ('Serbia', 3409673950),
 ('Mongolia', 3296470965.6),
 ('Georgia', 3087990080.3),
 ('Nigeria', 2957693969.5),
 ('Guatemala', 2911981987.8),
 ('Papua New Guinea', 2842193842.5),
 ('Ethiopia', 2681493007.3),
 ('El Salvador', 2574548482.3),
 ('Tunisia', 2422062635.8),
 ('Bosnia and Herzegovina', 2112748020.9),
 ('Uzbekistan', 2097517190.9),
 ('Jordan', 1990343479.2),
 ('Dominican Republic', 1978111141.2),
 ('Bulgaria', 1883205166.2),
 ('Costa Rica', 1776491747.9),
 ('Mauritius', 1757803962.2),
 ('Ghana', 1689328833.5),
 ('Senegal', 1661790101.6),
 ('Lao PDR', 1605959990.1),
 ('Paraguay', 1528508573.6),
 ('Azerbaijan', 1513813661.4),
 ('Zambia', 1502399702.8),
 ('Bolivia', 1421491255.2),
 ('Tanzania', 1388218481.4),
 ('Uganda', 1359705707.6),
 ('Myanmar', 1246429044.3),
 ('Nicaragua', 1185575296.8),
 ("Cote d'Ivoire", 1081936422.8),
 ('Macedonia, FYR', 875846538.5),
 ('Nepal', 854955604),
 ('Armenia', 845630723.8),
 ('Kyrgyz Republic', 837442293.4),
 ('Albania', 790248675.2),
 ('Cambodia', 775955981.3),
 ('Moldova', 769232867),
 ('Mozambique', 749659443.7),
 ('Sudan', 704940261.8),
 ('Jamaica', 661568432.2),
 ('Montenegro', 650720957.9),
 ('Benin', 648444772.9),
 ('Burkina Faso', 617436227.2),
 ('Niger', 613393210.2),
 ('Mali', 602617562.3),
 ('Mauritania', 587173043.9),
 ('Gabon', 519921205.7),
 ('Tajikistan', 467153429.2),
 ('Zimbabwe', 461632253.7),
 ('Madagascar', 446922027.4),
 ('Honduras', 412459703.3),
 ('Yemen, Rep.', 402113863),
 ('Congo, Dem. Rep.', 370323229.6),
 ('Rwanda', 327248280.2),
 ('Maldives', 324159093.3),
 ('Syrian Arab Republic', 307261900),
 ('Congo, Rep.', 247432137.7),
 ('Togo', 236837922.9),
 ('Kosovo', 232317825.8),
 ('Bhutan', 213258536.9),
 ('Chad', 207090418.3),
 ('Djibouti', 176522478.2),
 ('Guinea', 175441526.2),
 ('Algeria', 171185188.1),
 ('Liberia', 150961031.2),
 ('Botswana', 137995908),
 ('Malawi', 132165820.5),
 ('Cabo Verde', 109582071.9),
 ('Guyana', 108264665.5),
 ('Eswatini', 106108147.6),
 ('Iran, Islamic Rep.', 105885317),
 ('Belize', 105609924.9),
 ('Afghanistan', 100847181.9),
 ('Sierra Leone', 98339852.8),
 ('Gambia, The', 89552885.9),
 ('Lesotho', 80548591.6),
 ('Fiji', 66510192.6),
 ('Burundi', 64846467.3),
 ('Haiti', 61444338.4),
 ('Central African Republic', 53717612.9),
 ('Guinea-Bissau', 48265990.2),
 ('Grenada', 41250138.3),
 ('Vanuatu', 38626756),
 ('St. Lucia', 37459842.2),
 ('St. Vincent and the Grenadines', 33458473.7),
 ('Somalia', 32985034.3),
 ('Eritrea', 31110077.8),
 ('Solomon Islands', 30749703.9),
 ('Turkmenistan', 29132060.9),
 ('Timor-Leste', 21799986.4),
 ('Samoa', 21715408.4),
 ('Dominica', 21394158.2),
 ('Comoros', 13460035.4),
 ('Sao Tome and Principe', 10636848.5),
 ('Tonga', 10369910.6)]